# upstream frontend {
#     server discord_frontend:3000;
# }

upstream backend {
    server clients_go:8000;
}

upstream minio {
    server minio_db:9000;
}

server {
    listen 80;
 
    location /static/ {
        proxy_pass http://minio/;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        client_max_body_size 10M;
        proxy_connect_timeout 60;
        proxy_send_timeout 120;
        proxy_read_timeout 120;
    }

    location /api {
        proxy_pass http://backend/api;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ws {
        proxy_pass http://backend/api/ws;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade websocket;
        proxy_set_header Connection Upgrade;
    }

    # location / {
    #     proxy_pass http://frontend/;
    #     proxy_set_header   Host             $host;
    #     proxy_set_header   X-Real-IP        $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }
}