services:
  auth_go:
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    ports:
      - "44000:44000"
    image: auth-go-image
    container_name: auth_go
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - pg_db

  relations_go:
    build:
      context: .
      dockerfile: ./cmd/relations/Dockerfile
    ports:
      - "44002:44002"
    image: relations-go-image
    container_name: relations_go
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mongo_db

  clients_go:
    build:
      context: .
      dockerfile: ./internal/clients/Dockerfile
    ports:
      - "8000:8000"
    image: clients-go-image
    container_name: clients_go
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./files:/app/files

  mongo_db:
    image: mongo
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db
    environment:
      #- MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      #- MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5430:5432"
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data/
    networks:
      - app-network

  profile:
    build: services/profile
    command: >
      sh -c "poetry run alembic upgrade head && poetry run python3 -m main"
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app/app
volumes:
  pg_data:
  go_back:
  mongo_data:

networks:
  app-network:
    driver: bridge
